apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: ironmans.avengers.marvel
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: avengers.marvel
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: false
      # One and only one version must be marked as the storage version.
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                originalName:
                  type: string
                fathersName:
                  type: string
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                originalName:
                  type: string
                fathersName:
                  type: string
                gender:
                  type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: ironmans
    # singular name to be used as an alias on the CLI and for display
    singular: ironman
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Ironman
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - im